FROM openjdk:8u151-jdk-alpine3.7

# TEMPORAL
#EXPOSE 8070

ARG APP_PORT

EXPOSE $APP_PORT

ENV APP_HOME /usr/src/app

# TEMPORAL
COPY shopping-cart-0.0.1-SNAPSHOT.jar $APP_HOME/app.jar

WORKDIR $APP_HOME

ENTRYPOINT exec java -jar app.jar